post_install() {
  echo "The i915 kernel module will be available on reboot."
  echo "You can edit /etc/tmpfiles.d/i915-set-sriov-numvfs.conf to set the number of VFs on boot."
  echo "You can edit /etc/modprobe.d/i915-sriov-dkms.conf to set parameters for i915 and blocklisting xe."
  echo "Please refer to https://github.com/strongtz/i915-sriov-dkms/blob/master/README.md to set kernel parameters."
}

post_remove() {
  echo "The i915 kernel module will be removed on reboot."
}
