#!/bin/sh

if [ "$1" = "configure" ]; then
	if [ -z "$2" ]; then
		echo First configuration, installing for all kernels
		export autoinstall_all_kernels=1
	fi
fi

#DEBHELPER#
# Update initramfs on package configuration
case "$1" in
	configure)
		depmod -a
		if [ -x /usr/sbin/update-initramfs ]; then
			/usr/sbin/update-initramfs -u
		elif [ -x /usr/bin/update-initramfs ]; then
			/usr/bin/update-initramfs -u
		elif [ -x /sbin/update-initramfs ]; then
			/sbin/update-initramfs -u
		elif [ -x /bin/update-initramfs ]; then
			/bin/update-initramfs -u
		fi
		;;
esac