#!/bin/sh

#DEBHELPER#
# Update initramfs on package remove
case "$1" in
	remove)
		depmod -a
		if [ -x /usr/sbin/update-initramfs ]; then
			/usr/sbin/update-initramfs -u
		elif [ -x /usr/bin/update-initramfs ]; then
			/usr/bin/update-initramfs -u
		elif [ -x /sbin/update-initramfs ]; then
			/sbin/update-initramfs -u
		elif [ -x /bin/update-initramfs ]; then
			/bin/update-initramfs -u
		fi
		;;
esac