#!/bin/sh

if [ "$1" = "configure" ]; then
	export autoinstall_all_kernels=1
fi

#DEBHELPER#
command -v update-initramfs >/dev/null 2>&1 || exit 0
case "$1" in
	configure)
		depmod -a
		update-initramfs -u -k all
		;;
	*)
		;;
esac
