/* SPDX-License-Identifier: MIT */
/*
 * Copyright © 2024 Intel Corporation
 */

#ifndef _ABI_IOV_ACTIONS_MMIO_ABI_H_
#define _ABI_IOV_ACTIONS_MMIO_ABI_H_

#include "guc_communication_ctb_abi.h"

/*
 * MMIO relay VF/PF opcodes.
 */
#define IOV_OPCODE_VF2PF_MMIO_HANDSHAKE			0x01
#define IOV_OPCODE_VF2PF_MMIO_UPDATE_GGTT		0x02
#define IOV_OPCODE_VF2PF_MMIO_GET_RUNTIME		0x10

/*
 * VF2PF MMIO handshake message fields.
 */
#define VF2PF_MMIO_HANDSHAKE_REQUEST_MSG_LEN		4u
#define VF2PF_MMIO_HANDSHAKE_REQUEST_MSG_1_MAJOR	(0xffffu << 16)
#define VF2PF_MMIO_HANDSHAKE_REQUEST_MSG_1_MINOR	(0xffffu << 0)

#define VF2PF_MMIO_HANDSHAKE_RESPONSE_MSG_LEN		4u
#define VF2PF_MMIO_HANDSHAKE_RESPONSE_MSG_0_MBZ		GUC_HXG_RESPONSE_MSG_0_DATA0
#define VF2PF_MMIO_HANDSHAKE_RESPONSE_MSG_1_MAJOR	(0xffffu << 16)
#define VF2PF_MMIO_HANDSHAKE_RESPONSE_MSG_1_MINOR	(0xffffu << 0)

/*
 * VF2PF MMIO update GGTT message fields.
 */
#define VF2PF_MMIO_UPDATE_GGTT_REQUEST_MSG_LEN		4u
#define VF2PF_MMIO_UPDATE_GGTT_REQUEST_MSG_1_OFFSET	(0xfffffu << 12)
#define VF2PF_MMIO_UPDATE_GGTT_REQUEST_MSG_1_MODE	(0x3u << 10)
#define   MMIO_UPDATE_GGTT_MODE_DUPLICATE		0u
#define   MMIO_UPDATE_GGTT_MODE_REPLICATE		1u
#define   MMIO_UPDATE_GGTT_MODE_DUPLICATE_LAST		2u
#define   MMIO_UPDATE_GGTT_MODE_REPLICATE_LAST		3u
#define VF2PF_MMIO_UPDATE_GGTT_REQUEST_MSG_1_NUM_COPIES	(0x3ffu << 0)
#define VF2PF_MMIO_UPDATE_GGTT_REQUEST_MSG_2_PTE_LO	GUC_HXG_REQUEST_MSG_n_DATAn
#define VF2PF_MMIO_UPDATE_GGTT_REQUEST_MSG_3_PTE_HI	GUC_HXG_REQUEST_MSG_n_DATAn

#define VF2PF_MMIO_UPDATE_GGTT_RESPONSE_MSG_LEN		1u
#define VF2PF_MMIO_UPDATE_GGTT_RESPONSE_MSG_1_NUM_PTES	(0xffffffu << 0)

/*
 * VF2PF MMIO get runtime message fields.
 */
#define VF2PF_MMIO_GET_RUNTIME_REQUEST_MSG_LEN		4u
#define VF2PF_MMIO_GET_RUNTIME_REQUEST_MSG_n_OFFSETn	GUC_HXG_REQUEST_MSG_n_DATAn
#define VF2PF_MMIO_GET_RUNTIME_REQUEST_MSG_NUM_OFFSET	3u

#define VF2PF_MMIO_GET_RUNTIME_RESPONSE_MSG_LEN		4u
#define VF2PF_MMIO_GET_RUNTIME_RESPONSE_MSG_n_VALUEn	GUC_HXG_RESPONSE_MSG_n_DATAn
#define VF2PF_MMIO_GET_RUNTIME_RESPONSE_MSG_NUM_VALUE	3u

#endif /* _ABI_IOV_ACTIONS_MMIO_ABI_H_ */
