#include <linux/version.h>

#ifndef __ASSEMBLY__
#define LINUX_BACKPORT(__sym) backport_ ##__sym
#endif

#define MODULE_ABS_PATH(path) DKMS_MODULE_SOURCE_DIR/path

// We vendor our own copy of the GPUSVM module, so enable it here.
#ifdef CONFIG_DRM_GPUSVM
#undef CONFIG_DRM_GPUSVM
#endif
#ifdef CONFIG_DRM_GPUSVM_MODULE
#undef CONFIG_DRM_GPUSVM_MODULE
#endif
#define CONFIG_DRM_GPUSVM_MODULE 1

// Enable i915 driver and its features by default.
// The following values are based on the Arch Linux kernel config.
#ifdef CONFIG_DRM_I915
#undef CONFIG_DRM_I915
#endif
#ifdef CONFIG_DRM_I915_MODULE
#undef CONFIG_DRM_I915_MODULE
#endif
#define CONFIG_DRM_I915_MODULE 1

#ifdef CONFIG_DRM_I915_CAPTURE_ERROR
#undef CONFIG_DRM_I915_CAPTURE_ERROR
#endif
#define CONFIG_DRM_I915_CAPTURE_ERROR 1

#ifdef CONFIG_DRM_I915_COMPRESS_ERROR
#undef CONFIG_DRM_I915_COMPRESS_ERROR
#endif
#define CONFIG_DRM_I915_COMPRESS_ERROR 1

#ifdef CONFIG_DRM_I915_DP_TUNNEL
#undef CONFIG_DRM_I915_DP_TUNNEL
#endif
#define CONFIG_DRM_I915_DP_TUNNEL 1

#ifdef CONFIG_DRM_I915_FENCE_TIMEOUT
#undef CONFIG_DRM_I915_FENCE_TIMEOUT
#endif
#define CONFIG_DRM_I915_FENCE_TIMEOUT 10000

#ifndef CONFIG_DRM_I915_FORCE_PROBE
#define CONFIG_DRM_I915_FORCE_PROBE "*"
#endif

#ifdef CONFIG_DRM_I915_GVT
#undef CONFIG_DRM_I915_GVT
#endif
#define CONFIG_DRM_I915_GVT 1

#ifdef CONFIG_DRM_I915_GVT_KVMGT_MODULE
#undef CONFIG_DRM_I915_GVT_KVMGT_MODULE
#endif
#define CONFIG_DRM_I915_GVT_KVMGT_MODULE 1

#ifdef CONFIG_DRM_I915_HEARTBEAT_INTERVAL
#undef CONFIG_DRM_I915_HEARTBEAT_INTERVAL
#endif
#define CONFIG_DRM_I915_HEARTBEAT_INTERVAL 2500

#ifdef CONFIG_DRM_I915_MAX_REQUEST_BUSYWAIT
#undef CONFIG_DRM_I915_MAX_REQUEST_BUSYWAIT
#endif
#define CONFIG_DRM_I915_MAX_REQUEST_BUSYWAIT 8000

#ifdef CONFIG_DRM_I915_PREEMPT_TIMEOUT
#undef CONFIG_DRM_I915_PREEMPT_TIMEOUT
#endif
#define CONFIG_DRM_I915_PREEMPT_TIMEOUT 640

#ifdef CONFIG_DRM_I915_PREEMPT_TIMEOUT_COMPUTE
#undef CONFIG_DRM_I915_PREEMPT_TIMEOUT_COMPUTE
#endif
#define CONFIG_DRM_I915_PREEMPT_TIMEOUT_COMPUTE 7500

#ifdef CONFIG_DRM_I915_PXP
#undef CONFIG_DRM_I915_PXP
#endif
#define CONFIG_DRM_I915_PXP 1

#ifdef CONFIG_DRM_I915_REQUEST_TIMEOUT
#undef CONFIG_DRM_I915_REQUEST_TIMEOUT
#endif
#define CONFIG_DRM_I915_REQUEST_TIMEOUT 20000

#ifdef CONFIG_DRM_I915_STOP_TIMEOUT
#undef CONFIG_DRM_I915_STOP_TIMEOUT
#endif
#define CONFIG_DRM_I915_STOP_TIMEOUT 100

#ifdef CONFIG_DRM_I915_TIMESLICE_DURATION
#undef CONFIG_DRM_I915_TIMESLICE_DURATION
#endif
#define CONFIG_DRM_I915_TIMESLICE_DURATION 1

#ifdef CONFIG_DRM_I915_USERFAULT_AUTOSUSPEND
#undef CONFIG_DRM_I915_USERFAULT_AUTOSUSPEND
#endif
#define CONFIG_DRM_I915_USERFAULT_AUTOSUSPEND 250

#ifdef CONFIG_DRM_I915_USERPTR
#undef CONFIG_DRM_I915_USERPTR
#endif
#define CONFIG_DRM_I915_USERPTR 1

// Enable xe driver and its features by default.
// The following values are based on the Arch Linux kernel config.
#ifdef CONFIG_DRM_XE
#undef CONFIG_DRM_XE
#endif
#ifdef CONFIG_DRM_XE_MODULE
#undef CONFIG_DRM_XE_MODULE
#endif
#define CONFIG_DRM_XE_MODULE 1

#ifdef CONFIG_DRM_XE_DISPLAY
#undef CONFIG_DRM_XE_DISPLAY
#endif
#define CONFIG_DRM_XE_DISPLAY 1

#ifdef CONFIG_DRM_XE_DP_TUNNEL
#undef CONFIG_DRM_XE_DP_TUNNEL
#endif
#define CONFIG_DRM_XE_DP_TUNNEL 1

#ifdef CONFIG_DRM_XE_ENABLE_SCHEDTIMEOUT_LIMIT
#undef CONFIG_DRM_XE_ENABLE_SCHEDTIMEOUT_LIMIT
#endif
#define CONFIG_DRM_XE_ENABLE_SCHEDTIMEOUT_LIMIT 1

#ifdef CONFIG_DRM_XE_FORCE_PROBE
#undef CONFIG_DRM_XE_FORCE_PROBE
#endif
#define CONFIG_DRM_XE_FORCE_PROBE ""

#ifdef CONFIG_DRM_XE_GPUSVM
#undef CONFIG_DRM_XE_GPUSVM
#endif
#define CONFIG_DRM_XE_GPUSVM 1

#ifdef CONFIG_DRM_XE_JOB_TIMEOUT_MAX
#undef CONFIG_DRM_XE_JOB_TIMEOUT_MAX
#endif
#define CONFIG_DRM_XE_JOB_TIMEOUT_MAX 10000

#ifdef CONFIG_DRM_XE_JOB_TIMEOUT_MIN
#undef CONFIG_DRM_XE_JOB_TIMEOUT_MIN
#endif
#define CONFIG_DRM_XE_JOB_TIMEOUT_MIN 1

#ifdef CONFIG_DRM_XE_PAGEMAP
#undef CONFIG_DRM_XE_PAGEMAP
#endif
#define CONFIG_DRM_XE_PAGEMAP 1

#ifdef CONFIG_DRM_XE_PREEMPT_TIMEOUT
#undef CONFIG_DRM_XE_PREEMPT_TIMEOUT
#endif
#define CONFIG_DRM_XE_PREEMPT_TIMEOUT 640000

#ifdef CONFIG_DRM_XE_PREEMPT_TIMEOUT_MAX
#undef CONFIG_DRM_XE_PREEMPT_TIMEOUT_MAX
#endif
#define CONFIG_DRM_XE_PREEMPT_TIMEOUT_MAX 10000000

#ifdef CONFIG_DRM_XE_PREEMPT_TIMEOUT_MIN
#undef CONFIG_DRM_XE_PREEMPT_TIMEOUT_MIN
#endif
#define CONFIG_DRM_XE_PREEMPT_TIMEOUT_MIN 1

#ifdef CONFIG_DRM_XE_TIMESLICE_MAX
#undef CONFIG_DRM_XE_TIMESLICE_MAX
#endif
#define CONFIG_DRM_XE_TIMESLICE_MAX 10000000

#ifdef CONFIG_DRM_XE_TIMESLICE_MIN
#undef CONFIG_DRM_XE_TIMESLICE_MIN
#endif
#define CONFIG_DRM_XE_TIMESLICE_MIN 1
