#ifndef __EXTRAVERSION__
#define __EXTRAVERSION__

#ifndef EXTRAVERSION_MAJOR
#define EXTRAVERSION_MAJOR 0
#endif

#ifndef EXTRAVERSION_PATCHLEVEL
#define EXTRAVERSION_PATCHLEVEL 0
#endif

#define EXTRAVERSION(a,b) (((a) << 8) + (b))
#define EXTRAVERSION_CODE EXTRAVERSION(EXTRAVERSION_MAJOR,EXTRAVERSION_PATCHLEVEL)

#endif /* __EXTRAVERSION__ */
