#include_next <drm/display/drm_dp.h>
#ifndef __BACKPORT_DRM_DP_H__
#define __BACKPORT_DRM_DP_H__


#if LINUX_VERSION_CODE < KERNEL_VERSION(6, 19, 0)
# define DP_DSC_THROUGHPUT_MODE_0_DELTA_SHIFT 3 /* DP 2.1a, in units of 2 MPixels/sec */
# define DP_DSC_THROUGHPUT_MODE_0_DELTA_MASK  (0x1f << DP_DSC_THROUGHPUT_MODE_0_DELTA_SHIFT)

#define DP_DSC_BRANCH_CAP_SIZE 3
#endif

#if LINUX_VERSION_CODE < KERNEL_VERSION(7, 0, 0)
# define DP_PANEL_REPLAY_FULL_LINE_GRANULARITY		0xffff
#endif

#if LINUX_VERSION_CODE < KERNEL_VERSION(7, 2, 0)
#define PANEL_REPLAY_CONFIG3			0x11a /* DP 2.1 */
# define DP_PR_AS_SDP_SETUP_TIME_MASK		(3 << 6)
# define DP_PR_AS_SDP_SETUP_TIME_T1		(0 << 6)
# define DP_PR_AS_SDP_SETUP_TIME_DYNAMIC	(1 << 6) /* DP 2.1 Table 2-227 */
# define DP_PR_AS_SDP_SETUP_TIME_T2		(2 << 6)

#define DP_AS_SDP_OPERATION_MODE_MASK	GENMASK(1, 0)
#define DP_AS_SDP_LENGTH_MASK		GENMASK(5, 0)

# define DP_AS_SDP_FAVT_PAYLOAD_FIELDS_PARSING_SUPPORTED			BIT(2) /* 2.1 */
#endif

#endif /* __BACKPORT_DRM_DP_H__ */
